name: Deploy to Firebase App Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Setup Firebase
        run: npm install -g firebase-tools@latest
        
      - name: Deploy to Firebase App Hosting production
        run: |
          firebase apphosting:rollouts:create prod --git-branch main --project decision-copilot
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
