name: Deploy to Firebase App Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Deploy to Firebase App Hosting production
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DECISION_COPILOT }}' > /tmp/service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account.json
          npx firebase-tools@latest deploy --only apphosting --env production --project decision-copilot
        env:
          FIREBASE_CLI_PREVIEWS: apphosting
